### ISSUE TITLE
add /ping 

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#11]
https://www.spigotmc.org/resources/ping-command.47134/

**Comment by willcannotpaythebills** [comment]
link can be a example ig?

**Comment by gcurtiss** [comment]
you can see your ping in tab, it's the number next to your name

**Comment by willcannotpaythebills** [comment]
too lazy to make another issue but when u compile p3 in intellej the name is actually p2 lol. i have no idea whty

**Comment by gcurtiss** [comment]
maven pom project name is p2 because it was adapted from p2
