### ISSUE TITLE
Excessive amounts of containers in a single chunk causes extreme lag

### ISSUE THREAD

**Issue by gcurtiss** [gcurtiss/protocol3#24]
@ultra64cmy 

stash caused tps to drop below 1

repro:
- 14 chunks
- per chunk: 16 double chests wide, 4 double chests high
- fill all double chests with shulkers of any item 
- observe behavior

observed on avas.cc, mitigated by turning off item.illegal.agro and movement.chunkcheck. issue is exacerbated when one or more people are moving around in the chunk

idea: only check chunks when they are entered for the first time as opposed to checking a chunk on every movement

**Comment by gcurtiss** [comment]
idea 2: cache illegal items by taking an MD5 hash of the inventory of the item being scanned. store that MD5 hash, then compare every item against a session-only HashMap of MD5 hashes; if it's already present & valid, allow the item to exist without rebuilding it

**Comment by willcannotpaythebills** [comment]
server will shit itself even at sneaking speeds

**Comment by gcurtiss** [comment]
the feature causing lag is disabled rn @willcannotpaythebills

**Comment by ultra64cmy** [comment]
I have a branch that caches checked chunks per players. Will push that this afternoon after testing on my local server.

**Comment by gcurtiss** [comment]
@ultra64cmy you should wipe that cache every hour or so, otherwise it defeats the purpose

**Comment by ultra64cmy** [comment]
It's an LRU cache, so old chunks will be evicted as the players move around the world. I can see about making a periodic process to flush the cache if you think that's critical.

**Comment by gcurtiss** [comment]
no, an LRU will be fine

**Comment by ultra64cmy** [comment]
I included the flush period because I had already written most of it. You can disable it by setting the config value to -1.

**Comment by ultra64cmy** [comment]
https://github.com/gcurtiss/protocol3/blob/ca94614ccd6787b507fa2956d6c4d95f6c7ec8db/protocol3/src/main/java/protocol3/backend/ItemCheck.java#L62-L64

Looking at profiler output, this code is good to target for performance improvements. If there's some way we can identify that the item is a shulk using a different API that's faster we can get a 40%+ time improvement. Even just caching the result of `getBlockState()` in a local was enough to knock 15% off runtime.

**Comment by gcurtiss** [comment]
@ultra64cmy new fix knocked off most of the problem so im closing this issue but if you have further improvements to make submit a PR
