### ISSUE TITLE
avas.cc website has information on restrictions that don't match current version of P3

### ISSUE THREAD

**Issue by LysergikProductions** [gcurtiss/protocol3#25]
![image](https://user-images.githubusercontent.com/61183022/111754951-f13cb600-886e-11eb-9d01-26cff09142ee.png)

Besides corrections, we may consider adding mention of specifically lag machines being consequential to the player.

**Comment by gcurtiss** [comment]
dm 69

**Comment by gcurtiss** [comment]
fixed after too long
