### ISSUE TITLE
Add vanish for admins

### ISSUE THREAD

**Issue by gcurtiss** [gcurtiss/protocol3#30]
69 and I want to be secret and silent

if nobody else adds it i will but hey if i can delegate more work i will

**Comment by ultra64cmy** [comment]
I think it's easy to do this poorly and hard to do correctly. If you're open to using existing plugins, check out the feature list of [Super Vanish](https://www.spigotmc.org/resources/supervanish-be-invisible.1331/). It's [open source](https://github.com/LeonMangler/SuperVanish) as well so you can build it yourself.

**Comment by willcannotpaythebills** [comment]
supervanish doesnt work w java 15, or at least when i tested it. just a fyi :)
