### ISSUE TITLE
suicide and kys need to be implemented as synonyms for kill

### ISSUE THREAD

**Issue by ultra64cmy** [gcurtiss/protocol3#34]
`/suicide` and `/kys` are listed in `/help` but don't exist in the plugin. Should be a quick update to this code block here to add them:
https://github.com/gcurtiss/protocol3/blob/1e3411b9e1bb8bbffcb2b577d695edc00eb46f7c/protocol3/src/main/java/protocol3/Main.java#L100-L104

**Comment by gcurtiss** [comment]
doesn't work that way since you can only register one executor per command, but they are implemented as synonyms for kill, but in commands.yml
