### ISSUE TITLE
too autistic to make a pr so heres how to compile p3 for intellej

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#4]
1. Download the repo
2. Unzip the zip file and drag it to your IdeaProjects folder (C:\\User\IdeaProjects) 
3. Open the project. Select "Maven" when prompted.
4. Reopen the project. (Close it and reopen)
5. Build p3 using IDEA's Maven Projects view; View -> Tool Windows -> Maven Projects
6. Open p3 
7. Double click install.
8. Find the.jar file in your C:\\User\protocol3\target

**Comment by gcurtiss** [comment]
ok
