### ISSUE TITLE
make discord link a config option

### ISSUE THREAD

**Issue by ultra64cmy** [gcurtiss/protocol3#42]
Change the code below to fetch from `Config`. Bonus points: If the user doesn't have a Discord set, disable the command.

https://github.com/gcurtiss/protocol3/blob/632692f6b00ef4ecd52176a2bcd8f201a8ce76d5/protocol3/src/main/java/protocol3/commands/Discord.java#L18

**Comment by soapsofthoneyandmilk** [comment]
^ same w /vote

**Comment by gcurtiss** [comment]
ok
