### ISSUE TITLE
performance issue - removing wither skulls can be expensive

### ISSUE THREAD

**Issue by ultra64cmy** [gcurtiss/protocol3#47]
https://github.com/gcurtiss/protocol3/blob/28ae291095cffacc582d6d677d1e8c6a9dd863cb/protocol3/src/main/java/protocol3/events/LagPrevention.java#L79

When the server is under load (lots of players and/or traveling) removing wither skulls can be slow due to `getEntities()` taking a long time. Refer to the following profiler snapshot:

https://spark.lucko.me/n27gnQ7f3H

Search for `removeOldSkulls` and note the amount of time spent in `CraftWorld.getEntities()`. If there's a way to collect only the wither skulls without using this API there is potential for major time savings.

**Comment by gcurtiss** [comment]
as it stands right now this is a non-issue, i'll open this back up in the event it becomes an issue
