### ISSUE TITLE
dumbass forgot a step lmao

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#5]
Clone the repo
Open the project. Select "Maven" when prompted.
Reopen the project. (Close it and reopen)
Build p3 using IDEA's Maven Projects view; View -> Tool Windows -> Maven Projects
Open p3, then Lifestyle
Double click install.
An .jar file will be produced in /target called p3-3-shaded.jar
Place this .jar in your plugins directory on your server.
Kill yourself for using IntelliJ like a brainlet

**Comment by timoreo22** [comment]
Fixed in commit 3102b81
