### ISSUE TITLE
Players up for vote mute, but not yet actually muted, are unable to start a new vote mute

### ISSUE THREAD

**Issue by wetsausages** [gcurtiss/protocol3#50]
Repro:
Start a vote on someone
Don't finish the vote

I think blocking muted players from voting/starting votes was originally intended, but I don't think it was intended to apply those penalties before the vote successfully passes. Further, players in this state are still able to vote on vote mutes, just not start them.

**Comment by soapsofthoneyandmilk** [comment]
i made a fucking bug report on this already

**Comment by gcurtiss** [comment]
this is a different bug retard @soapsofthoneyandmilk

**Comment by gcurtiss** [comment]
wait this isnt' a bug lol

you're seeing the vote mute cooldown so that vote mutes cant be started b2b
