### ISSUE TITLE
Vanilla stacked cursed books get deleted by the illegal stack functions

### ISSUE THREAD

**Issue by LysergikProductions** [gcurtiss/protocol3#6]
Using a grindstone, users can stack cursed books. This is a vanilla feature / bug and does not break the game. P3 currently deletes these stacks.

STR:

1) Place two identical cursed books in both grindstone slots
2) Remove the stack of 2 books from the result slot
3) Place stack in a shulker box
4) Mine the shulker box and observe issue

Results:
The stack is either deleted completely or reduced to stack size of 1

Notes:
No need to investigate further as simply adding && !item.getType().equals(wtv id for cursed books) to the condition for rebuilding stacks should fix this issue

**Comment by gcurtiss** [comment]
Fixed, will be pushed when p3.2.2 is ready.
