### ISSUE TITLE
bug: /ignore registers as a invalid command when typed

### ISSUE THREAD

**Issue by willcannotpaythebills** [gcurtiss/protocol3#63]
![image](https://user-images.githubusercontent.com/77316348/117521180-4ccb1c00-af61-11eb-8e2b-5cfca1650a96.png)
how to repro:
find someone to ignore
type /ignore

**Comment by timoreo22** [comment]
This should be fixed now

**Comment by willcannotpaythebills** [comment]
ogey closing issue
